services:
    postgres:
        image: postgres:16.1
        restart: always
        volumes:
            - ov-data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ov-db

volumes:
    ov-data:
